<?php
include_once 'includes/content/media.php';
$pageTitle = "Portfolio";
head_content($pageTitle, "Here are some links to some of the more professional things that I worked on. All links open in a new window. Enjoy.");
?>
<?php
write_media("Clickable Map","<h3>Flex</h3><p><small>(No live link available)</small></p><p>An example of a Flash/Flex based project that allows the production editor to update articles  by modifying a XML files.</p>","","assets/images/portfolio/clickablemap.jpg",false,true);
write_media("Product Finder","<h3>Flex</h3><p>A Flex piece that was designed to help the customer choose which type of machinery they needed. It used similar options that the customer had in their printed catalog. Based upon which selections you make in the left hand column, it will ghost out products that will not suit your needs. The information to handle all this is stored as an XML file.</p>","portfolio/innovatis/index.html","assets/images/portfolio/innovatis.jpg",false,true);
write_media('<a href="bioreactordefender.php" target="_blank">Bioreactor Defender game </a>&amp; Kenyon Hoag Site','<h3>Flash Website and Flash Game</h3><p><small>(Link to <a href="bioreactordefender.php" target="_blank"><i class="glyphicon glyphicon-new-window"></i> game</a> available)</small></p><p>I programmed the game, which is a separate Flash file that run in the background of the Flash site, which I also made. All the top scores are stored in a MySQL database. The Flash also grab&#39;s the company&#39;s Twitter information and displays it.</p>',"","assets/images/portfolio/kenyonhoag.jpg",false,true);
write_media("Frontlines: Fuel Of War", "<h3>C#, C++, Python, and Unreal Script</h3><p>Besides working in Python with the continuous builder, working on shaders for video playback in in the game, and the installer, while at KAOS Studios I got to write the Autorun interface. It was created with C# and was locaizable for the dozen of languages that the game was released in. Also, written in C# was an crash reporter that would FTP crash logs for beta testing.</p>", "http://en.wikipedia.org/wiki/Frontlines:_Fuel_of_War","assets/images/portfolio/frontlines.jpg",false,true);
write_media("Interferon Force",'<h3>Video Editing/Flash and HTML Website</h3><p><small>(No live link available, click <a href="http://web.archive.org/web/20120219225026/http://www.interferonforce.com/" target="_blank"><i class="glyphicon glyphicon-new-window"></i> here</a> for a <a href="http://web.archive.org" target="_blank"><i class="glyphicon glyphicon-new-window"></i> Wayback Machine</a> archive)</small></p><p>I took over working on the site. I had to recreate the intro from a video file into Flash. I also had to work with the supplied art, and make the HTML layouts and Flash animations for the site.</p>',"","assets/images/portfolio/interferonforce.jpg",false,true);
write_media("Interferon Source","<h3>HTML/CSS Website</h3><p><small>(No live link available)</small></p><p>Here is the framework of a site that was designed around a shopping cart system developed by another party. Working with-in their guidelines, the site was designed and coded to allow their developers the ability to easily intergrate the design into their code for dynamic page genertation. Also, some of the Flash elements were also recreated in Javascript, allowing both standard browsers and iPhone/cell phone browser to experience the site. A forum is also set up and styled to match the design of the website.</p>","","assets/images/portfolio/interferonsource.jpg",false,true);
write_media("Emilie Jerard","<h3>Flex/Flash/MySQL Database</h3><p><small>(No live link available)</small></p><p>For this site, a content management system was created in Flex to help the client upload and organize news, press releases and images for the online store. The site then uses all the data from a MySQL database to populate all the images of what items are available.</p>","","assets/images/portfolio/emiliejerard.jpg",false,true);
?>
<?php end_content(); ?>
